FROM node:14

# Set the working directory in the container
WORKDIR /usr/src/app/front/

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install the application dependencies
RUN npm install

# Copy the application code into the container
COPY . .

RUN npm install serve --global
# Build the application
RUN npm run build

# Expose the port that the app will run on
EXPOSE 3003

# Define the command to run the application
CMD ["serve", "-p 3003"]
